"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CalendarDays, Check, FileCheck2, Headphones, Info, MessageCircle, Phone, ShieldCheck, Sparkles } from "lucide-react";
import { useDemo } from "@/components/demo-provider";
import { RiskBadge } from "@/components/customer-table";
import { channelLabels, dateLabel, money, outcomeLabels, type Customer } from "@/lib/demo-data";

export function CustomerDetail({ customer }: { customer: Customer }) {
  const { reference } = useDemo();
  const [view, setView] = useState<"all" | "messages" | "decisions">("all");
  const hasCommitment = customer.contacted && ["PAYMENT_COMMITMENT", "ALTERNATIVE_DATE"].includes(customer.outcome);
  const reply = customer.outcome === "HUMAN_ESCALATION" ? "Prefiero hablar con una persona, por favor." : customer.outcome === "FOLLOW_UP_REQUIRED" ? "Necesito revisar mis gastos antes de darle una fecha." : customer.outcome === "ALTERNATIVE_DATE" ? "Este mes se me complicó. ¿Podemos revisar otra fecha?" : "Sí, puedo realizar el pago de mi cuota.";
  const factorTotal = customer.factors.reduce((sum, factor) => sum + factor.contribution, 0);
  return <div className="page-enter"><Link className="back-link" href="/riesgo"><ArrowLeft size={15} /> Atención preventiva</Link><div className="customer-heading"><span className={`avatar large-avatar avatar-${customer.channel}`}>{customer.initials}</span><div><span className="eyebrow">PERFIL FICTICIO · {customer.id}</span><h1>{customer.name}</h1><p>{customer.product} <span>·</span> Canal preferido: {channelLabels[customer.channel]}</p></div><RiskBadge band={customer.band} /></div>
    {customer.isControl && <div className="info-strip"><ShieldCheck size={18} /><p>Este perfil pertenece a la cohorte de control. No se han realizado contactos ni conversaciones.</p></div>}
    {!customer.isControl && customer.outcome === "HUMAN_ESCALATION" && <div className="info-strip"><Headphones size={18} /><p>Solicitud de atención humana en el escenario de demostración. Automatización en pausa.</p></div>}
    <div className="detail-grid"><div className="detail-main"><section className="panel loan-panel"><div className="panel-heading"><h2>Contexto del cliente</h2><span className="neutral-badge">Datos de ejemplo</span></div><div className="loan-stats"><div><span>Saldo del crédito</span><strong>{money(customer.balanceCents)}</strong></div><div><span>Próxima cuota</span><strong>{money(customer.installmentCents)}</strong></div><div><span>Vencimiento</span><strong>{dateLabel(reference, customer.dueInDays)}</strong><small>En {customer.dueInDays} días</small></div></div></section>
      <section className="panel timeline-panel"><div className="panel-heading"><div><span className="eyebrow">EL CONTEXTO, EN UN SOLO LUGAR</span><h2>Historia de la gestión</h2></div>{customer.channel === "whatsapp" ? <MessageCircle size={20} /> : <Phone size={19} />}</div><div className="timeline-filter segmented">{([{ value: "all", label: "Todos los eventos" }, { value: "messages", label: "Conversación" }, { value: "decisions", label: "Decisiones" }] as const).map(tab => <button key={tab.value} aria-pressed={view === tab.value} onClick={() => setView(tab.value)}>{tab.label}</button>)}</div><p className="timeline-date">{dateLabel(reference, -customer.activityDaysAgo, true)} · Secuencia ilustrativa</p>
      <div className="timeline">
        {view !== "messages" && <div className="timeline-event"><span className="timeline-icon"><Sparkles size={15} /></span><div><strong>Señal preventiva identificada</strong><p>Prioridad {customer.score}/100. El contexto incluye vencimiento, historial de pagos y mayor atraso.</p><small>Origen: fixture de riesgo · versión demo</small></div></div>}
        {view !== "messages" && <div className="timeline-event"><span className="timeline-icon"><ShieldCheck size={15} /></span><div><strong>{customer.isControl ? "Contacto excluido por cohorte de control" : customer.contacted ? "Intervención preventiva programada" : "Sin intervención programada"}</strong><p>{customer.isControl ? "Se mantiene el perfil sin contacto para la futura comparación de resultados." : customer.contacted ? `Canal: ${channelLabels[customer.channel]}. Esta decisión precede a la conversación del ejemplo.` : "El perfil no tiene contactos en el periodo de demostración."}</p><small>Referencia de política: v1 · Registro simulado</small></div></div>}
        {view !== "decisions" && customer.contacted && <><div className="message-bubble agent-message"><div><span className="message-author">Asistente digital</span><span>{channelLabels[customer.channel]}</span></div><p>{customer.channel === "whatsapp" ? "Le escribe" : "Le habla"} el asistente digital de Bancoagrícola. Queremos acompañarle con su próxima cuota de {money(customer.installmentCents)}, que vence el {dateLabel(reference, customer.dueInDays)}.</p><small>Mensaje de demostración</small></div>{customer.outcome !== "NO_ANSWER" && <div className="message-bubble customer-message"><div><span className="message-author">{customer.name}</span><span>Perfil ficticio</span></div><p>{reply}</p></div>}</>}
        {view !== "messages" && customer.contacted && <div className="timeline-event"><span className="timeline-icon success"><Check size={15} /></span><div><strong>{outcomeLabels[customer.outcome]}</strong><p>{hasCommitment ? "El escenario incluye un acuerdo confirmado y un comprobante de registro ficticio." : customer.outcome === "HUMAN_ESCALATION" ? "La solicitud del cliente deriva el caso a una persona y pausa los contactos automáticos." : customer.outcome === "NO_ANSWER" ? "El escenario no incluye una respuesta del cliente ni un acuerdo de pago." : "No se ha confirmado una fecha concreta. El escenario queda pendiente de seguimiento."}</p><small>{hasCommitment ? `Comprobante demo: REC-${customer.id}` : "Cierre del escenario de demostración"}</small></div></div>}
        {view === "messages" && !customer.contacted && <div className="empty-state"><MessageCircle size={25} /><h3>No hay conversaciones</h3><p>Este perfil no ha sido contactado.</p></div>}
      </div></section>
    </div><div className="detail-side"><section className="panel score-panel"><div className="panel-heading"><h2>Por qué esta prioridad</h2><Info size={17} /></div><div className="detail-score"><strong>{customer.score}<small>/100</small></strong><RiskBadge band={customer.band} /></div><div className="score-scale"><span style={{ width: `${customer.score}%` }} /></div><p className="score-disclaimer">Señal simulada de atención, no un score crediticio.</p><h3>Los 3 factores principales</h3>{customer.factors.map((factor, index) => <div className="factor" key={factor.label}><span>0{index + 1}</span><div><strong>{factor.label}</strong><p>{factor.detail}</p></div><b>+{factor.contribution}</b></div>)}<p className="score-remainder">Otros factores: {customer.score - factorTotal} puntos. Datos predefinidos para explorar la explicabilidad.</p></section>
      {hasCommitment && <section className="panel agreement-panel"><span className="agreement-icon"><FileCheck2 size={21} /></span><h2>Un acuerdo concreto</h2><p>{outcomeLabels[customer.outcome]}</p><strong className="agreement-amount">{money(customer.installmentCents)}</strong><span className="agreement-status"><Check size={14} />{customer.commitmentKept ? "Pago registrado · demo" : "Pendiente de cumplimiento"}</span><div className="info-caption"><CalendarDays size={15} /> Fecha acordada de ejemplo: {dateLabel(reference, customer.dueInDays)}</div></section>}
      <Link className="policy-detail-link" href="/politicas"><ShieldCheck size={19} /><span>Consultar políticas de contacto</span><ArrowRight size={16} /></Link>
    </div></div><p className="data-note">Este perfil y su historia son completamente ficticios. La vista no envía mensajes ni modifica acuerdos.</p></div>;
}
